buttons:
  KEY_SPACE: b    #jump
  KEY_LEFTSHIFT: zl   #squid
  BTN_LEFT: zr    #shoot
  BTN_RIGHT: r    #bomb
  KEY_Q: r_stick   #special
  KEY_ENTER: l    #match menu
  KEY_E: plus
  KEY_R: minus
  KEY_TAB: x      #map
  BTN_MIDDLE: l_stick
  #dpad
  KEY_UP: up
  KEY_DOWN: down
  KEY_LEFT: left
  KEY_RIGHT: right

  #some other nice binds
  KEY_LEFTBRACE: l
  KEY_RIGHTBRACE: r
  KEY_LEFTCTRL: a
  KEY_LEFTALT: y

left_stick:
  KEY_A: left
  KEY_D: right
  KEY_W: up
  KEY_S: down

motion:
  sensitivity: 1
